db setting done
Double-Slash/5th-final-team2.5 pull request #18
Opened 2021-01-02 12:14 UTC by jjmmll0727

db 세팅완료 하였습니다.(db 구조는 개발하면서 수정될 수 있음) 익일부터 api, routing 정리하여 프론트팀과 공유하도록 하겠습니다.

2021-01-02 12:41 UTC, kuk941025 requested changes
Schema를 작성하시면서 다른 개발자도 알수있게 문서화를 해주시면 좋을것같아요! 현재 DB구조는 한글로만 되어있어서 영어 필드를 보니까 감이 안오는 필드명도 있네요ㅠㅠ
그리고 프론트에서는 변수이름을 camelcase를 사용하고 있습니다! 나중에 서버와 통신할때 편하게 필드명은 camcelcase로 변경해주세요..!

2021-01-02 12:41 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +  },
field랑 area가 어떤 값을 가지고 있는건가요??

2021-01-02 12:41 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +module.exports = mongoose.model('club', UserSchema);
`ClubSchema`를 model로 컴파일 해줘야되지 않나요??

2021-01-02 12:41 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +  comment: [
comment의 array이니까 `comments`가 더 어울려보입니다!

2021-01-02 12:41 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +  },
날짜를 저장하니까 `Date`이 더 어울리지 않을까요??

2021-01-02 12:41 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +  },
`likes`의 디폴드 값을 0으로 주면 좋을것같아요

2021-01-02 12:41 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +  ],
`CommentarieSchema`에서도 array정의되어 있고 `comment` 필드도 array로 정의되어 있어요. `CommentarieSchema`에서는 array로 정의하지 않아도 될것같습니다!

2021-01-02 12:41 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +    logo_image: {type: mongoose.SchemaTypes.Url},
`SchemaTypes`에 `Url`이 있나요?! mongoose document에서는 찾을수가 없네요ㅠ

2021-01-02 12:41 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +    unique: true,
`name`이 동아리 이름을 말하는게 맞을까요?? 다른 동아리끼리 겹치는 이름을 봐서 unique로 하는건 한번 생각해봐야 될것같아요🤔

2021-01-02 13:31 UTC, jjmmll0727 commented on packages/dodam-server/models/Clubs.js
> +  ],
댓글에 여러 답글이 달릴 수 있다고 생각하여 배열 형태로 세팅했습니다!

2021-01-02 13:31 UTC, jjmmll0727 commented on packages/dodam-server/models/Clubs.js
> +    logo_image: {type: mongoose.SchemaTypes.Url},
https://www.npmjs.com/package/mongoose-type-url 
실제로 돌려봐야 하겠지만 한번 참고해주시면 감사하겠습니다!

2021-01-02 13:35 UTC, jjmmll0727 commented
camelcase로 다시 정리했습니다! 한번 더 확인 부탁드립니다.

2021-01-02 13:44 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +  ],
`CommentarieSchema`도 배열이고 `comment`도 배열로 되어있어서요. 이러면 이중배열이 되지 않나요??
```javascript
const CommentaireSchema = new Schema({
  commentarie: [
    type: String
  ]
});
const ClubSchema = new Schema({
  ...
  comment: [ CommentaireSchema ],
  ...
})
```

2021-01-02 13:44 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +    logo_image: {type: mongoose.SchemaTypes.Url},
참고해봤는데 `mongoose-type-url`을 불러오는 코드가 생략되어 있습니다..!

2021-01-02 13:48 UTC, jjmmll0727 commented on packages/dodam-server/models/Clubs.js
> +  ],
comment 배열안에 답글 배열이 있는 형태입니다!

2021-01-02 13:52 UTC, jjmmll0727 commented on packages/dodam-server/models/Clubs.js
> +    logo_image: {type: mongoose.SchemaTypes.Url},
감사합니다! 제가 놓쳤습니다 ㅠ

2021-01-02 14:02 UTC, jjmmll0727 commented
한번더 확인 부탁드립니다!

2021-01-03 04:27 UTC, kuk941025 requested changes
필드명을 lowerCamelCase로 변경부탁드려요 첫글자는 소문자로!
그리고 필드명에 대한 설명을 `fieldnaming` 파일을 만들어 설명을 하셨는데, 필드명에 대한 설명은 파일이 아닌 노션 docs 부분에 올려주세요!

2021-01-03 04:27 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +})
지금은 문자열만 저장하고 있는데 작성자의 이름도 댓글에 표시해줘야 될것같아서 작성자 아이디값과 이름을 함께 저장하는게 좋아보여요!

2021-01-03 04:27 UTC, kuk941025 commented on packages/dodam-server/models/Users.js
>    },
이메일 스키마를 아래와 같은 validation을 추가하는건 어떨까요? 
```javascript
const validateEmail = function(email) {
    var re = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    return re.test(email)
};

const EmailSchema = new Schema({
    email: {
        type: String,
        trim: true,
        lowercase: true,
        unique: true,
        required: 'Email address is required',
        validate: [validateEmail, 'Please fill a valid email address'],
        match: [/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/, 'Please fill a valid email address']
    }
});
```

2021-01-03 04:27 UTC, kuk941025 commented on packages/dodam-server/models/Clubs.js
> +  },
`Date.now`와 `Date.now()` 차이를 설명하는 [링크](https://stackoverflow.com/questions/35501273/what-is-the-difference-between-date-now-and-date-now-in-mongoose) 입니다. 
`Date.now()`를 사용하면 스키마를 생성한 시간이 저장돼서 `Date.now`가 맞는것같아요

2021-01-03 06:47 UTC, Lim-Changi commented on packages/dodam-server/models/Users.js
>    },
저도 예전에 이메일 스키마 작성할때 Validation 넣어서 작업했었는데 DB 에러는 최대한 안나는게 좋다고 현직자분꼐서 스키마에 정의하기보다는 프론트에서 처리하거나 백에서 body로 값을 받을때 DB에 저장하기 전에 체크하는게 좋다고 들었습니다!

2021-01-03 07:53 UTC, jjmmll0727 commented on packages/dodam-server/models/Users.js
>    },
이에 대한 준규님의 의견도 듣고 싶습니다!

2021-01-03 08:11 UTC, kuk941025 commented on packages/dodam-server/models/Users.js
>    },
프론트에서도 처리할 예정입니다 하지만 프론트는 쉽게 뚫릴수있어 백엔드에서 validation을 꼭 체크해줘야되는걸로 알고있어요. 
Body에서 확인하는거랑 validation에서 확인하는거랑은 어떤차이가 있을까요?? 새로운 document 생성되기 전에 validate하는거랑 body받고 체크하는거랑 같다는 생각이 들어서요!

2021-01-03 08:14 UTC, jjmmll0727 commented on packages/dodam-server/models/Users.js
>    },
제가 직접 짜봤는데 애초에 validation에서 걸리는 속성 값이면 document가 생성조차 되지 않는 차이가 있습니다..!

2021-01-03 08:23 UTC, kuk941025 commented on packages/dodam-server/models/Users.js
>    },
Db 저장하기전에 body를 체크해서 validate을 실패하는경우에도 document를 생성안하지 않나요??

2021-01-03 08:26 UTC, jjmmll0727 commented on packages/dodam-server/models/Users.js
>    },
네 맞습니다! 그러면 일단은 스키마에서 validation을 세팅해놓고 개발 작업 진행하겠습니다! 새롭게 pr 올려놓겠습니다  merge 부탁드릴께요!

2021-01-03 08:29 UTC, jjmmll0727 commented
re-request 했습니다! 확인부탁드려요 ㅎㅎ 감사합니다!

2021-01-03 12:03 UTC, kuk941025 approved these changes
master에 올라가는 코드에서 정말 필요한게 아니라면 `console.log`는 없는게 좋을것같아요..! 그리고 `comment`, `reply` 콜렉션 두개를 만들어서 댓글을 관리하는게 어색해보입니다. `comment` 와 `reply`에서 겹치는 부분이 많아서 `comment` 콜렉션 하나로 해결할 수 있을것같아요. 다음 PR에서 수정부탁드릴게요 수고하셨습니다 👏 👏

2021-01-03 12:03 UTC, merged

2021-01-03 12:06 UTC, jjmmll0727 commented
스키마를 두개로 나눈 이유는 각 스키마 마다 회원의 정보를 저장하는 것이 필수적이기 때문에 일차적으로 위와 같이 세팅했습니다. 늦은 시간까지 확인해주셔서 감사합니다!!