회원가입,로그인,동아리생성,동아리수정,댓글생성,답글생성 구현완료
Double-Slash/5th-final-team2.5 pull request #19
Opened 2021-01-06 18:04 UTC by Lim-Changi

## 요약
커밋내용까지 구현했고 Postman 테스트 완료했습니다 Eslint 적용을 시도해봤지만 결국 못해서 일단은 시간이 더 중요한것 같아서 적용 못한채로 PR 했습니다. 추후에 더 작업하는내용있으면 그때 다시 eslint 적용해보겠습니다

## 설명
세부 설명은 API 문서로 설명드리겠습니다

2021-01-07 13:20 UTC, kuk941025 requested changes
prettier로 포맷팅이 안돼서 tab indent도 4로 설정이 되어있고 읽기가 힘들어요😢
eslint 적용하는데 어떤 문제가 있었는지 알수있을까요..? eslint가 사전에 잡아주는 문제가 많기 때문에 eslint에 익숙해지는게 앞으로 개발하시는데 도움이 많이 될거에요!

2021-01-07 13:20 UTC, kuk941025 commented on packages/dodam-server/.gitignore
> +package-lock.json
`package-lock.json`을 포함해주셔야 합니다!

2021-01-07 13:20 UTC, kuk941025 commented on packages/dodam-server/controller/clubController.js
> +        }
동아리 로고와 대표 이미지 url인가요??  삼항 조건 연산자를 if condition으로 넣는건 좋은 방법이 아닌것같아요.. 함수로 빼는게 좋아보입니다. 
그리고 이미지가 없는 경우도 있는건가요?!

2021-01-07 13:20 UTC, kuk941025 commented on packages/dodam-server/controller/clubController.js
> +        );
```js
const newClub = await Club.create(req.body)
```
이런식으로 새로운 클럽 document을 생성하게 할순 없을까요? 너무 전달되는 필드가 많아요ㅠ

2021-01-07 13:20 UTC, kuk941025 commented on packages/dodam-server/controller/clubController.js
> +        );
그리고 위에서 if문으로  body를 하나씩 확인하고 있는데 `create`할때 조건에 어긋나는 body params가 있으면 `mongoose`에서 오류를 던져주니까 확인을 안해도 될것같아요. 오류를 이미 catch하고 있으니까요

2021-01-07 13:20 UTC, kuk941025 commented on packages/dodam-server/controller/clubController.js
> +        }
여기서도 위 코드와 중복되는 로직이 발생하네요 함수로 빼는게 나아보입니다!

2021-01-07 13:20 UTC, kuk941025 commented on packages/dodam-server/controller/clubController.js
> +        );
이 부분도 전달하는 필드가 너무 많은데 다른 방법이 있는 한번 찾아보는게 좋을것같습니다!🤔

2021-01-07 13:20 UTC, kuk941025 commented on packages/dodam-server/controller/userController.js
> +    if (!checkPw) {
👍  버그가 있었군요ㅜ

2021-01-07 13:20 UTC, kuk941025 commented on packages/dodam-server/package.json
> +    "fs": "0.0.1-security",
`fs`는 nodejs에 기본으로 제공되는 모듈이에요.. 이 dependency는 삭제 부탁드립니다.

2021-01-07 13:20 UTC, kuk941025 commented on packages/dodam-server/routes/club/index.js
> +      limits: { fileSize: 5 * 1024 * 1024 }
이건 알아보기 싶게 주석으로 업로드 가능한 파일크기를 설명해주시면 좋을것같아요!

2021-01-07 23:12 UTC, Lim-Changi commented on packages/dodam-server/package.json
> +    "fs": "0.0.1-security",
넵! 삭제하겠습니다

2021-01-07 23:13 UTC, Lim-Changi commented on packages/dodam-server/routes/club/index.js
> +      limits: { fileSize: 5 * 1024 * 1024 }
넵 5 MB 로 주석처리하겠습니다

2021-01-07 23:15 UTC, Lim-Changi commented on packages/dodam-server/.gitignore
> +package-lock.json
앗 넵 다시포함하겠습니다

2021-01-07 23:20 UTC, Lim-Changi commented on packages/dodam-server/controller/clubController.js
> +        }
넵 함수로 만들어서 처리하겠습니다

2021-01-07 23:26 UTC, Lim-Changi commented on packages/dodam-server/controller/clubController.js
> +        );
동아리 정보 입력창에서 입력가능한 정보가 많은거 같아서요 ,, 위의 필드들을 다 받긴 해야할것 같은데 전체필드를 하나의 변수로 묶어서 DB CREATE 하는것은 가능할 것 같습니다.

2021-01-07 23:31 UTC, Lim-Changi commented on packages/dodam-server/controller/clubController.js
> +        );
넵 혹시나 필수 필드값이 비어있는 값으로 들어왔을때 읽기 힘든 DB오류보단 따로 서버에서 처리해서 클라한테 보내주는것이 좋다고 생각했습니다! 그럼 mongoose 가 처리할수 있도록 뺴겠습니다

2021-01-07 23:38 UTC, Lim-Changi commented on packages/dodam-server/controller/clubController.js
> +        }
동아리 로고사진과 포스터사진입니다! 넵넵 함수로 처리해서 create 아래 update 에 있는 Image로직도 바꾸겠습니다! 이미지가 첨부되지 않은 경우에는 DB에 위 두 변수가 빈값으로 들어갑니다 혹시 특별한 문제가 있을까요?

2021-01-07 23:47 UTC, Lim-Changi commented
> prettier로 포맷팅이 안돼서 tab indent도 4로 설정이 되어있고 읽기가 힘들어요😢
> eslint 적용하는데 어떤 문제가 있었는지 알수있을까요..? eslint가 사전에 잡아주는 문제가 많기 때문에 eslint에 익숙해지는게 앞으로 개발하시는데 도움이 많이 될거에요!

제가 최근에 시간적여유가 너무 없어서,, 기능들 최대한 구현하면서 eslint prettier로 다시 천천히 해보겠습니다!

2021-01-09 07:26 UTC, jjmmll0727 commented on packages/dodam-server/controller/userController.js
> +    if (!checkPw) {
확인 감사합니다!

2021-01-11 17:10 UTC, jjmmll0727 reviewed
수고 많으셨습니다!!

2021-01-12 14:38 UTC, kuk941025 approved these changes
`prettier`랑 `eslint` 잘 적용된게 맞을까요?? 만약 커밋할때 husky가 실행되지 않으면 루트에서 husky를 지웠다가 다시 설치하면 좋을것같아요. 커밋할때마다 자동으로 코드 포맷팅을 해줘서요.
코드는 전체적으로 깔끔해진것같아요~ 고생하셨습니다 👍

2021-01-12 14:38 UTC, kuk941025 commented on packages/dodam-server/controller/clubController.js
> +        let logoImage = await getFilePath(req,'logoImage');
이 변수도 `const`를 사용할 수 있을것같아요!

2021-01-12 14:38 UTC, kuk941025 commented on packages/dodam-server/controller/clubController.js
> +        const newClub = await Club.create(clubValues);
결국 이 부분은 아래처럼 수정을 못하는건가요..?ㅠㅠ 계속 신경이 쓰이네요🤔 
```js
const newClub = await Club.create({...req.body, representativeImage, logoImage})
```

2021-01-12 14:38 UTC, kuk941025 commented on packages/dodam-server/controller/clubController.js
> +            userLikeData.save();
비동기적으로 실행되는데 안 기다리고 바로 결과값을 리턴하면 저장중 문제가 생겨도 프론트는 오류를 모르지 않을까요?!

2021-01-12 14:38 UTC, kuk941025 commented on packages/dodam-server/controller/clubController.js
> +        let logoImage = await getFilePath(req,'logoImage');
이 부분도 `const`를 사용할 수 있을것같아요

2021-01-12 14:38 UTC, merged